[2025-02-04T08:22:37.726+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_dag.load_task manual__2025-02-04T08:22:35.294760+00:00 [queued]>
[2025-02-04T08:22:37.730+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_dag.load_task manual__2025-02-04T08:22:35.294760+00:00 [queued]>
[2025-02-04T08:22:37.730+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2025-02-04T08:22:37.740+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): load_task> on 2025-02-04 08:22:35.294760+00:00
[2025-02-04T08:22:37.743+0000] {standard_task_runner.py:57} INFO - Started process 26678 to run task
[2025-02-04T08:22:37.745+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'load_dag', 'load_task', 'manual__2025-02-04T08:22:35.294760+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/load_dag.py', '--cfg-path', '/tmp/tmpef475cf_']
[2025-02-04T08:22:37.745+0000] {standard_task_runner.py:85} INFO - Job 16: Subtask load_task
[2025-02-04T08:22:37.768+0000] {task_command.py:410} INFO - Running <TaskInstance: load_dag.load_task manual__2025-02-04T08:22:35.294760+00:00 [running]> on host codespaces-039a13
[2025-02-04T08:22:37.804+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='load_dag' AIRFLOW_CTX_TASK_ID='load_task' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T08:22:35.294760+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T08:22:35.294760+00:00'
[2025-02-04T08:22:37.805+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-04T08:22:37.805+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo -e ".separator ","\n .import --skip 1 /workspaces/hands-on-introduction-data-engineering-4395021/lab/orchestrated/airflow-transform-data.csv top_level_domains" | sqlite3 /workspaces/hands-on-introduction-data-engineering-4395021/lab/orchestrated/airflow-load-db.db']
[2025-02-04T08:22:37.811+0000] {subprocess.py:86} INFO - Output:
[2025-02-04T08:22:37.815+0000] {subprocess.py:93} INFO - Parse error near line 2: near ".": syntax error
[2025-02-04T08:22:37.815+0000] {subprocess.py:93} INFO -   .import --skip 1 /workspaces/hands-on-introduction-data-engineering-4395021/la
[2025-02-04T08:22:37.815+0000] {subprocess.py:93} INFO -   ^--- error here
[2025-02-04T08:22:37.815+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-02-04T08:22:37.820+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-04T08:22:37.822+0000] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=load_dag, task_id=load_task, execution_date=20250204T082235, start_date=20250204T082237, end_date=20250204T082237
[2025-02-04T08:22:37.831+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 16 for task load_task (Bash command failed. The command returned a non-zero exit code 1.; 26678)
[2025-02-04T08:22:37.836+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-02-04T08:22:37.844+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
